# Generated by Django 3.1.7 on 2021-04-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('condition', models.CharField(max_length=50, verbose_name='Condition')),
                ('quantity', models.IntegerField(verbose_name='Quantity product')),
                ('location', models.CharField(max_length=50)),
                ('data_posted', models.DateField(verbose_name='Date')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('html_description', models.TextField(null=True, verbose_name='HTML Description')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.category')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
